### ISSUE TITLE
It broke!

### ISSUE THREAD

**Issue by vanilla-coder** [yownas/sd-webui-lua#4]
The webui is a moving target to be sure, things keep changing and breaking stuff. Currently only the basic hardcoded method in your addon works. When trying to use a processing object it fails with  ValueError: An event handler (lua_run) didn't receive enough output values (needed: 3, received: 2).

If you haven't lost all interest in this project, please fix it, it's a great tool for tinkering with image generation and experimenting with crazy novel ideas! All Stable Diffusion nerds in the world depend on you! (Well, at least ONE nerd out there appreciates this wonderful addon and is tearing his hair out trying to figure out what's wrong with it).

Make it work again, pretty please?

**Comment by yownas** [comment]
Oh. I'll take a look at this after work.

Which webui are you using? a1111 or sd.next? I've been tinkering with other things, so it's been a while since I touched this extension, but I guess I have to get back to it since all the nerds in the world are depending on it. :D

**Comment by vanilla-coder** [comment]
Much appreciated! The Lua addon is great for messing around with the SD internals without getting smelly entrails all over the kitchen. I would have written it myself if I had the talent! ;-)

I'm using a1111, but thinking about switching to sd.next the next time I need to update/reinstall.

**Comment by yownas** [comment]
Did a very quick test. It seems to work in sd.next. I didn't have time to check what has been changed in a1111, but I'll look at it later.

**Comment by yownas** [comment]
Woop! Fixed in c865384

An update should hopefully stop it from breaking.

**Comment by vanilla-coder** [comment]
Runs like butter. My inner Mad Scientist can now be unleashed.

Thanks a lot for making this addon, and for the excellent "customer service"!
